import '@uirouter/angularjs'
import 'angular';
import 'angular-animate';
import 'angular-breadcrumb';
import 'angular-drag-and-drop-lists';
import 'angular-messages';
import 'angular-mocks';
import 'angular-resource';
import 'angular-sanitize';
import 'angular-ui-notification';
import 'angular-ui-tinymce';
import 'bootstrap';
import 'jquery';
import 'ng-currency';
import 'ng-file-upload';
import 'ng-idle';
import 'ng-img-crop';
import 'ui-bootstrap4';
