import { Document } from 'mongoose';
import ICapabilityDocument from '../../../capabilities/server/interfaces/ICapabilityDocument';
import ICapabilitySkillDocument from '../../../capabilities/server/interfaces/ICapabilitySkillDocument';
import IUserDocument from '../../../users/server/interfaces/IUserDocument';

export default interface IOrgDocument extends Document {
	name: string;
	dba: string;
	address: string;
	address2: string;
	city: string;
	province: string;
	postalcode: string;
	businessNumber: string;
	businessJurisdiction: string;
	fullAddress: string;
	contactName: string;
	contactEmail: string;
	contactPhone: string;
	description: string;
	website: string;
	orgImageURL: string;
	skills: string[];
	badges: string[];
	capabilities: ICapabilityDocument[];
	capabilitySkills: ICapabilitySkillDocument[];
	metRFQ: boolean;
	isCapable: boolean;
	isAcceptedTerms: boolean;
	owner: IUserDocument;
	created: Date;
	createdBy: IUserDocument;
	updated: Date;
	updatedBy: IUserDocument;
	members: IUserDocument[];
	admins: IUserDocument[];
	invited: string[];
	invitedUsers: IUserDocument[];
	invitedNonUsers: string[];
	emaillist?: [string];
}
