'use strict';

import angular from 'angular';

export interface IDataService {
	cities: string[];
}

angular.module('core').service('DataService', () => {
	return {
		cities: [
			'Victoria',
			'Vancouver',
			'100 Mile House',
			'Abbotsford',
			'Armstrong',
			'Barriere',
			'Burnaby',
			'Campbell River',
			'Castlegar',
			'Central Saanich',
			'Chetwynd',
			'Chilliwack',
			'Clearwater',
			'Coldstream',
			'Colwood',
			'Comox',
			'Coquitlam',
			'Courtenay',
			'Cranbrook',
			'Creston',
			'Dawson Creek',
			'Delta',
			'Duncan',
			'Elkford',
			'Enderby',
			'Esquimalt',
			'Fernie',
			'Fort St. James',
			'Fort St. John',
			'Grand Forks',
			'Greenwood',
			'Highlands',
			'Hope',
			'Houston',
			"Hudson's Hope",
			'Invermere',
			'Kamloops',
			'Kelowna',
			'Kent',
			'Kimberley',
			'Kitimat',
			'Ladysmith',
			'Lake Country',
			'Langford',
			'Langley',
			'Langley',
			'Lantzville',
			'Lillooet',
			'Logan Lake',
			'Mackenzie',
			'Maple Ridge',
			'Merritt',
			'Metchosin',
			'Mission',
			'Nanaimo',
			'Nelson',
			'New Hazelton',
			'New Westminster',
			'North Cowichan',
			'North Saanich',
			'North Vancouver',
			'North Vancouver',
			'Northern Rockies',
			'Oak Bay',
			'Parksville',
			'Peachland',
			'Penticton',
			'Pitt Meadows',
			'Port Alberni',
			'Port Coquitlam',
			'Port Edward',
			'Port Hardy',
			'Port Moody',
			'Powell River',
			'Prince George',
			'Prince Rupert',
			'Qualicum Beach',
			'Quesnel',
			'Revelstoke',
			'Richmond',
			'Rossland',
			'Saanich',
			'Salmon Arm',
			'Sechelt',
			'Sicamous',
			'Sidney',
			'Smithers',
			'Sooke',
			'Spallumcheen',
			'Sparwood',
			'Squamish',
			'Stewart',
			'Summerland',
			'Surrey',
			'Taylor',
			'Terrace',
			'Tofino',
			'Trail',
			'Tumbler Ridge',
			'Ucluelet',
			'Vanderhoof',
			'Vernon',
			'View Royal',
			'Wells',
			'West Kelowna',
			'West Vancouver',
			'White Rock',
			'Williams Lake'
		]
	} as IDataService;
});
